documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "package-lock.json"
          - "package.json"

typescript:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.ts"
          - "**/*.tsx"
          - "**/*.mts"
          - "**/*.cts"
          - "**/*.d.ts"
